---
name: 'Restore Images'
description: 'Restores cached images'
inputs:
  cache:
    description: 'Location of the cache'
    required: false
    default: '~/image-cache'
  working-directory:
    description: 'Working directory to run in'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up the cache
      id: image-cache
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
      with:
        path: ${{ inputs.cache }}
        key: image-cache-${{ github.sha }}

    - name: Restore images from cache
      if: steps.image-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        for archive in ${{ inputs.cache }}/*.tar*; do docker load -i $archive; done
        cp ${{ inputs.cache }}/.image.* ${{ inputs.working-directory }}/package/
