name: 'End to End'
description: 'Runs end to end tests with multiple clusters'
inputs:
  k8s_version:
    description: 'Version of Kubernetes to use for clusters'
    required: false
    default: '1.17.17'
  using:
    description: 'Various options to pass via using="..."'
    required: false
  working-directory:
    description: 'Working directory to run in'
    required: false
    default: '.'
  target:
    description: 'Target for make'
    required: false
    default: 'e2e'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Reclaiming free space"
        # Clean up tools we don't need for our CI to free up more space on the hosted runner
        rm -rf /opt/ghc /usr/share/dotnet /usr/share/swift
        df -h
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Disable swap"
        sudo swapoff -a
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Report available RAM"
        free -h
        echo "::endgroup::"

    - name: Install WireGuard specific modules
      shell: bash
      run: |
        [[ "${{ inputs.using }}" =~ "wireguard" ]] || exit 0
        echo "::group::Installing WireGuard modules"
        sudo apt install -y linux-headers-$(uname -r) wireguard
        sudo modprobe wireguard
        echo "::endgroup::"

    - name: Run E2E deployment and tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CLUSTERS_ARGS: --k8s_version="${{ inputs.k8s_version }}"
      run: |
        make "${{ inputs.target }}" using="${{ inputs.using }}"
