---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.15"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.16"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.17"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.18"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    target-branch: "release-0.14"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.14 tracks the 0.25 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.26.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.15"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.15 tracks the 0.26 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.27.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.16"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.16 tracks the 0.27 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.28.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.17"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.17 tracks the 0.29 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.30.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.18"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.18 tracks the 0.30 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.31.0-alpha.0"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns:
          - "*"
    ignore:
      # These are included by k8s.io/client-go
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
  - package-ecosystem: gomod
    directory: "/tools"
    schedule:
      interval: weekly
    groups:
      tools:
        patterns:
          - "*"
