---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.13"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.14"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.15"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    target-branch: "release-0.14"
    directory: "/"
    schedule:
      interval: weekly
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.14 tracks the 0.25 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.26.0-alpha.0"
  - package-ecosystem: gomod
    target-branch: "release-0.15"
    directory: "/"
    schedule:
      interval: weekly
    allow:
      # Pick up k8s.io updates
      - dependency-name: k8s.io/client-go
    ignore:
      # 0.15 tracks the 0.26 branch
      - dependency-name: k8s.io/*
        versions: ">= 0.27.0-alpha.0"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # These are included by k8s.io/client-go
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
