---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.12"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.13"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.14"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
