name: 'Prepare host'
description: 'Prepares the GitHub action runner for the submariner e2e testing'
inputs:
  cabledriver:
    description: 'Install any system modules for specific cable drivers'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Reclaim free space
      shell: bash
      run: |
        # cleanup 30GB+ of tools we don't need for our CI
        rm -rf /opt/ghc /usr/share/dotnet /usr/share/swift
        df -h
        free -h

    - name: Install WireGuard kernel module (only in WireGuard jobs)
      if: ${{ inputs.cabledriver == 'wireguard' }}
      shell: bash
      run: |
        sudo apt install -y linux-headers-$(uname -r) wireguard
        sudo modprobe wireguard
