---
extends: default

rules:
  line-length:
    max: 140
    ignore: gh-actions/e2e/action.yaml # TODO: Delete once fixed
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /vendor
  /scripts/shared/resources/cluster*-config.yaml
  /scripts/shared/resources/prometheus/bundle.yaml

strict: true
