---
extends: default

rules:
  line-length:
    max: 140
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /vendor
  /prometheus
  /scripts/shared/resources/cluster*-config.yaml

strict: true
