---
extends: default

rules:
  line-length:
    max: 140
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /nexodus
  /vendor
  /scripts/shared/resources/cluster*-config.yaml
  /scripts/shared/resources/prometheus/bundle.yaml
