FROM quay.io/submariner/shipyard-linting:devel

ENV DAPPER_ENV="GITHUB_SHA MAKEFLAGS" \
    DAPPER_SOURCE=/go/src/github.com/submariner-io/shipyard DAPPER_DOCKER_SOCKET=true
ENV DAPPER_OUTPUT=${DAPPER_SOURCE}/output SCRIPTS_DIR=${DAPPER_SOURCE}/scripts/shared

WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["/opt/shipyard/scripts/entry"]
CMD ["sh"]
