# Calculate versions; these can be overridden
CUTTING_EDGE := release-0.12
DEV_VERSION := dev
override CALCULATED_VERSION := $(BASE_BRANCH)-$(shell git rev-parse --short=12 HEAD)
VERSION ?= $(CALCULATED_VERSION)

export CUTTING_EDGE DEV_VERSION VERSION

print-version:
	@echo CALCULATED_VERSION=$(CALCULATED_VERSION)
	@echo VERSION=$(VERSION)

.PHONY: print-version
