# Calculate versions; these can be overridden
CUTTING_EDGE := devel
DEV_VERSION := dev
override CALCULATED_VERSION := $(shell git describe --tags --dirty="-$(DEV_VERSION)" --exclude="*$(CUTTING_EDGE)*" --exclude="latest")
VERSION ?= $(CALCULATED_VERSION)

export CUTTING_EDGE DEV_VERSION VERSION
