name: 'Upgrades End to End'
description: 'Runs an upgrade procedure, followed by end to end tests with multiple clusters'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Reclaiming free space"
        # Clean up tools we don't need for our CI to free up more space on the hosted runner
        rm -rf /opt/ghc /usr/share/dotnet /usr/share/swift
        df -h
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Disable swap"
        sudo swapoff -a
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Report available RAM"
        free -h
        echo "::endgroup::"

    - shell: bash
      run: |
        make upgrade-e2e
