---
name: 'Release Images'
description: 'Builds images and uploads them to the public registry'
inputs:
  username:
    description: 'User name for the registry'
    required: true
  password:
    description: 'Password for the registry'
    required: true
  image_args:
    description: 'Additional image building arguments'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU (to support building on non-native architectures)
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
    - name: Set up buildx
      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
    - name: Build new images
      # This needs to be kept separate so that the release stage runs using the new Shipyard base image
      shell: bash
      env:
        IMAGES_ARGS: --nocache ${{ inputs.image_args }}
      run: |
        echo "::group::Build new images"
        make images multiarch-images
        echo "::endgroup::"
    - name: Release newly built images
      shell: bash
      env:
        QUAY_USERNAME: ${{ inputs.username }}
        QUAY_PASSWORD: ${{ inputs.password }}
      # Pass RELEASE_ARGS on the call, since GITHUB_REF set in the `env` directive doesn't get properly expanded
      run: make release-images RELEASE_ARGS="--tag '${GITHUB_REF##*/}'"
