---
name: 'Release Images'
description: 'Builds images and uploads them to the public registry'
inputs:
  username:
    description: 'User name for the registry'
    required: true
  password:
    description: 'Password for the registry'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "DEBUG_PRINT=true" >> $GITHUB_ENV
    - name: Set up QEMU (to support building on non-native architectures)
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
    - name: Set up buildx
      uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20
    - name: Build new images
      # This needs to be kept separate so that the release stage runs using the new Shipyard base image
      shell: bash
      run: |
        echo "::group::Build new images"
        make images multiarch-images USE_CACHE=false
        echo "::endgroup::"
    - name: Release newly built images
      shell: bash
      env:
        QUAY_USERNAME: ${{ inputs.username }}
        QUAY_PASSWORD: ${{ inputs.password }}
      # Pass GITHUB_REF on the call, since when it's set in the `env` directive it doesn't get properly expanded
      run: make release-images TAG="${GITHUB_REF##*/}"
