---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummypod
  namespace: ${ns}
spec:
  selector:
    matchLabels:
      app: dummypod
  template:
    metadata:
      labels:
        app: dummypod
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: dummypod
          image: ${SUBM_IMAGE_REPO}/nettest:${SUBM_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
      restartPolicy: Always
