---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  replicas: 1
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
        - name: netshoot
          image: ${SUBM_IMAGE_REPO}/nettest:${SUBM_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - 1h
      restartPolicy: Always
