---
name: 'Post Mortem'
description: 'Autopsy'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Report available disk space"
        df -h
        echo "::endgroup::"
        echo "::group::Report available RAM"
        free -h
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Running post mortem"
        make post-mortem
        echo "::endgroup::"

    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: submariner-gather
        path: gather_output
