---
name: 'Post Mortem'
description: 'Autopsy'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Report available disk space"
        df -h
        echo "::endgroup::"
        echo "::group::Report available RAM"
        free -h
        echo "::endgroup::"

    - shell: bash
      run: |
        echo "::group::Running post mortem"
        make post-mortem
        echo "::endgroup::"

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: submariner-gather
        path: gather_output
