#!/bin/bash
set -e

source "${SCRIPTS_DIR}/lib/debug_functions"

# shellcheck disable=SC2064 # We want the current values
trap "chown -R $DAPPER_UID:$DAPPER_GID ." exit

mkdir -p bin dist output

if [ -e "./scripts/$1" ]; then
    ./scripts/"$@"
else
    "$@"
fi


