#!/bin/bash
set -e

source "${SCRIPTS_DIR}/lib/debug_functions"

# shellcheck disable=SC2064 # We want the current values
trap "chown -R $DAPPER_UID:$DAPPER_GID ." exit

mkdir -p bin dist output

if [ -e "./scripts/$1" ]; then
    command="./scripts/$1"
else
    command="$1"
fi

# This ends the GHA group that started in Makefile.dapper
[[ -z "$CI" ]] || echo "::endgroup::"
shift
"$command" "$@"
