---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: submariner-subscription
  namespace: ${SUBM_NS}
spec:
  installPlanApproval: Manual
  name: ${OPERATOR_NAME}
  source: submariner-catalog-source
  sourceNamespace: ${MARKETPLACE_NAMESPACE}
