---
name: 'Commit Size'
description: 'Make sure no commit in the pull request goes over a certain size'
inputs:
  size:
    description: 'Total maximum size of commit (lines added+removed).'
    required: false
    default: '500'
runs:
  using: "composite"
  steps:
    - name: Make sure the size of each commit doesn't pass the desired size
      shell: bash
      run: |
        set -e
        # Fetch 'origin' to get all commits for size checking
        git fetch -q -n origin

        result=0
        commits_range=${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
        sum_commit() { git diff --numstat ${1} ${1}^ | awk '{ sum += $1 + $2 } END { print sum }'; }
        for commit in $(git log --pretty="format:%H" ${commits_range}); do
            if [[ $(git cat-file -p "${commit}" | grep -c "^parent ") -gt 1 ]]; then
                echo "Ignoring merge commit ${commit}"
                continue
            fi

            size=$(sum_commit ${commit})
            printf "Size of commit %s (%d) " "${commit}" "${size}"
            if [[ ${size} -gt ${{ inputs.size }} ]]; then
                echo "is larger than the allowed size ${{ inputs.size }}"
                result=1
                continue
            fi

            echo "is within allowed size ${{ inputs.size }}"
        done
        exit $result
