---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ${cs}
  namespace: ${MARKETPLACE_NAMESPACE}
spec:
  sourceType: grpc
  image: ${iib}
  displayName: ${cs}
  publisher: Submariner.io (Test)
  updateStrategy:
    registryPoll:
      interval: 5m
