#!/bin/bash
set -e

#
# The purpose of this script is to ensure that dapper-base:latest is updated and available locally
# and if dapper-base is modified we make sure it's rebuilt and tagged locally so any next
# execution through dapper will have the new image.
#

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-quay.io/submariner}
local_image=${REPO}/shipyard-dapper-base:${TAG}
latest_image=${REPO}/shipyard-dapper-base:latest

# Always pull latest image from the repo, so that it's layers may be reused.
docker pull ${latest_image}
docker tag ${latest_image} ${local_image}

# Rebuild the image to update any changed layers and tag it back so it will be used.
docker build -t ${local_image} --cache-from ${latest_image} -f package/Dockerfile.dapper-base .
docker tag ${local_image} ${latest_image}

