#!/bin/bash
set -e

source $(dirname $0)/shared/lib/debug_functions
source $(dirname $0)/shared/lib/version

function load_image() {
    docker pull ${1}:latest
    docker tag ${1}:latest ${1}:$VERSION
}

load_image quay.io/submariner/submariner
load_image quay.io/submariner/submariner-route-agent
load_image quay.io/submariner/submariner-globalnet

${SCRIPTS_DIR}/deploy.sh "$@"
