#!/bin/bash
set -e

source ${SCRIPTS_DIR}/lib/debug_functions

trap "chown -R $DAPPER_UID:$DAPPER_GID ." exit

mkdir -p bin dist output

if [ -e ./scripts/$1 ]; then
    ./scripts/"$@"
else
    "$@"
fi


