#!/bin/bash
set -e

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/find_functions

PACKAGES="$(find_go_pkg_dirs --no-trailing-dots "*.go")"

if [[ $(goimports -l ${PACKAGES} | wc -l) -gt 0 ]]; then
    echo Incorrect formatting
    echo These are the files with formatting errrors:
    goimports -l ${PACKAGES}
    echo These are the formatting errors:
    goimports -d ${PACKAGES}
    exit 1
fi

golangci-lint run

# SC2154 is excluded to avoid false positives based on our use of global variables
shellcheck -e SC2154 scripts/shared/lib/*
