#!/bin/bash
set -e

source $(dirname $0)/shared/lib/debug_functions
source $(dirname $0)/shared/lib/version

cd $(dirname $0)/..
echo "Downloading go modules to cache ----"
go mod download
echo "Download finished ------------------"
echo ""
go mod vendor
