#!/bin/bash
set -e

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/version

echo "Downloading go modules to cache ----"
go mod download
echo "Download finished ------------------"
echo ""
go mod vendor
