FROM quay.io/submariner/shipyard-dapper-base-deps

ENV SHIPYARD_DIR=/opt/shipyard/ SCRIPTS_DIR=/opt/shipyard/scripts

# Copy CI deployment scripts into image to share with all submariner-io/* projects
WORKDIR $SCRIPTS_DIR
COPY scripts/shared/ .
COPY Makefile.inc ${SHIPYARD_DIR}
