---
name: Testing

on:
  pull_request:

permissions: {}

env:
  DEBUG_PRINT: true
jobs:
  clusters:
    name: sysctl
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Show the value of net.ipv6.conf.all.forwarding
        run: sysctl net.ipv6.conf.all.forwarding
      
      - name: Show the value of net.ipv6.conf.all.disable_ipv6
        run: sysctl net.ipv6.conf.all.disable_ipv6

      - name: Enable net.ipv6.conf.all.forwarding
        run: sudo sysctl -w net.ipv6.conf.all.forwarding=1
      
      - name: Show the value of net.ipv6.conf.all.forwarding
        run: sysctl net.ipv6.conf.all.forwarding
