---
name: Testing

on:
  pull_request:

permissions: {}

env:
  DEBUG_PRINT: true
jobs:
  clusters:
    name: Clusters
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Deploy clusters
        run: make clusters TIMEOUT=1m

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

      - name: Clean up clusters
        run: make clean-clusters

  compilation:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Test the compile.sh script
        run: make script-test SCRIPT_TEST_ARGS="test/scripts/compile/test.sh"

  deployment:
    name: Deployment
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
        deploytool: ['operator', 'helm']
        extra-toggles: ['']
        include:
          - extra-toggles: air-gap
          - extra-toggles: air-gap
            globalnet: globalnet
          - extra-toggles: air-gap
            lighthouse: lighthouse
          - extra-toggles: air-gap
            ovn: ovn
          - extra-toggles: dual-stack
          - extra-toggles: ovn
          - deploytool: operator
            extra-toggles: lighthouse
          - deploytool: helm
            extra-toggles: lighthouse
          - extra-toggles: load-balancer
          - extra-toggles: prometheus
    steps:
      - name: Reclaim space on GHA host (if the job needs it)
        if: ${{ matrix.ovn != '' }}
        run: rm -rf /usr/share/dotnet

      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: true

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Deploy clusters and Submariner
        run: make deploy using="${{ matrix.globalnet }} ${{ matrix.deploytool }} ${{ matrix.extra-toggles }}" TIMEOUT=1m

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

      - name: Clean up deployment
        run: make clean-clusters

  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Run E2E deployment and tests
        run: make e2e

      - name: Post mortem
        if: failure()
        uses: ./gh-actions/post-mortem

  mutliple-gateways-support:
    name: Multiple gateways support
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Deploy clusters and test cloud-prepare
        run: make script-test SCRIPT_TEST_ARGS="test/scripts/cloud-prepare/test.sh"

      - name: Clean up deployment
        run: make clean-clusters

  post-mortem:
    name: Post mortem
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Deploy some clusters
        run: make clusters

      - name: Test the post_mortem.sh script
        run: make script-test SCRIPT_TEST_ARGS="test/scripts/post_mortem/test.sh"

