---
name: YAML Linting
on: pull_request

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    name: YAML Linting
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: make yamllint
